version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - default

  go-app:
    platform: linux/amd64
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    networks:
      - default

networks:
  default:
    driver: bridge